# Generated by Django 6.0.2 on 2026-02-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
    ]
