# Generated by Django 6.0.2 on 2026-02-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_submission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
    ]
