# Generated by Django 6.0.2 on 2026-02-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_submission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='editorial',
            field=models.TextField(blank=True, help_text='Solution explanation shown after AC.'),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256, help_text='Memory limit in MB.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compilation Error', 'Compilation Error'), ('Memory Limit Exceeded', 'Memory Limit Exceeded')], default='Pending', max_length=25),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='judge.tag'),
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Memory Limit Exceeded', 'Memory Limit Exceeded')], max_length=25)),
                ('actual_output', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Time in seconds.', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='Peak memory in MB.', null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='judge.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.testcase')),
            ],
            options={
                'ordering': ['test_case_number'],
            },
        ),
    ]
